Repository honeycombio/refinery, pull requests merged in 2021-03, with the labels that each got.

#217 Update README with recommendation to use IPs when DNS is unreliable or slow
  README.md
Labels: status: review needed, type: documentation, version: no bump

#220 Fix YAML config issues
  sample/rules.go
  sample/rules_test.go
Labels: type: bug, version: bump patch

#223 guard against nil pointer dereference
  route/route.go
Labels: type: bug, version: bump patch

#218 only publish to s3 when releasing
  .circleci/config.yml
Labels: version: no bump

#225 Add test for OTLP handler, including spans with no status
  route/route_test.go
Labels: version: no bump

#226 Add dependabot
  .github/dependabot.yml
Labels: type: maintenance, version: no bump

#234 Prepare v1.1.0 release
  CHANGELOG.md
Labels: status: review needed, version: bump minor
