Repository honeycombio/refinery, pull requests merged in 2021-11, with the labels that each got.

#342 Add an --interface-names flag
  cmd/refinery/main.go
  collect/collect_test.go
Labels: type: enhancement

#347 Bump libhoney-go to v1.15.6
  go.mod
  go.sum
Labels: type: maintenance, version: bump minor

#348 Prepares v1.6.0 release
  CHANGELOG.md
Labels: type: maintenance, version: no bump

#352 Revert "Use alpine as base image (#343)"
  .ko.yaml
Labels: type: bug, version: bump patch

#356 Update dependabot to monthly
  .github/dependabot.yml
Labels: type: maintenance, version: no bump, merge at will

#341 Replace internal duplicated code with Husky
  go.mod
  go.sum
  internal/opentelemetry-proto-gen/README.md
  internal/opentelemetry-proto-gen/collector/logs/v1/logs_service.pb.go
  internal/opentelemetry-proto-gen/collector/logs/v1/logs_service.pb.gw.go
  internal/opentelemetry-proto-gen/collector/metrics/v1/metrics_service.pb.go
  internal/opentelemetry-proto-gen/collector/metrics/v1/metrics_service.pb.gw.go
  internal/opentelemetry-proto-gen/collector/trace/v1/trace_config.pb.go
  internal/opentelemetry-proto-gen/collector/trace/v1/trace_service.pb.go
  internal/opentelemetry-proto-gen/collector/trace/v1/trace_service.pb.gw.go
  internal/opentelemetry-proto-gen/common/v1/common.pb.go
  internal/opentelemetry-proto-gen/logs/v1/logs.pb.go
  internal/opentelemetry-proto-gen/metrics/experimental/configservice.pb.go
  internal/opentelemetry-proto-gen/metrics/v1/metrics.pb.go
  internal/opentelemetry-proto-gen/resource/v1/resource.pb.go
  internal/opentelemetry-proto-gen/trace/v1/trace.pb.go
  route/errors.go
  route/otlp_trace.go
  route/otlp_trace_test.go
  route/route.go
Labels: type: enhancement, version: bump minor

#360 Prepare v1.7.0
  CHANGELOG.md
Labels: type: maintenance, version: no bump
