Repository honeycombio/refinery, pull requests merged in 2021-08, with the labels that each got.

#299 Add span.kind when ingesting OTLP
  route/otlp_trace.go
Labels: version: bump minor

#302 Prepare v1.3.1 release
  CHANGELOG.md
  RELEASE.md
Labels: version: bump patch, type: maintenance

#304 Add OSS lifecycle badge
  OSSMETADATA
  README.md
Labels: version: no bump
