Repository honeycombio/refinery, pull requests merged in 2021-07, with the labels that each got.

#282 update changelog for 1.3.0
  CHANGELOG.md
Labels: status: review needed, type: maintenance

#279 Add support for OTLP over HTTP/protobuf
  route/errors.go
  route/otlp_trace.go
  route/otlp_trace_test.go
  route/route.go
  route/route_test.go
Labels: status: review needed, type: enhancement, version: bump minor

#291 Prepare v1.4.0 release
  CHANGELOG.md
Labels: type: maintenance, version: bump minor
