Repository honeycombio/refinery, pull requests merged in 2021-10, with the labels that each got.

#326 prepare 1.5.0 release
  CHANGELOG.md
Labels: type: maintenance, version: no bump

#324 Patch for race condition on map access
  metrics/prometheus.go
Labels: type: bug, status: review needed

#333 [dev/ci] test in dev and CI the same way
  .circleci/config.yml
  Makefile
Labels: type: maintenance, version: no bump

#337 Prepare v1.5.2 release
  CHANGELOG.md
Labels: version: bump patch, type: maintenance

#338 Re-add missing docker login when publishing
  .circleci/config.yml
Labels: type: maintenance, version: no bump
