Repository honeycombio/refinery, pull requests merged in 2021-05, with the labels that each got.

#248 Verify that sample rate trace field key is specified, if needed.
  config/config_test.go
  config/sampler_config.go
Labels: type: enhancement, version: bump minor

#249 Move from garyburd Redigo to supported redigo
  cmd/test_redimem/main.go
  go.mod
  go.sum
  internal/peer/redis.go
  internal/redimem/redimem.go
Labels: version: no bump

#250 Add 'meta.refinery.local_hostname' to all spans
  app/app_test.go
  config/config.go
  config/config_test.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  transmit/transmit.go
Labels: status: review needed, version: bump minor

#254 make insecure TLS settings a config option
  config/config.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  internal/peer/redis.go
Labels: version: bump minor

#247 Remove redundant peer/api suffix from response error metric
  transmit/transmit.go
Labels: version: bump minor
