Repository honeycombio/refinery, pull requests merged in 2022-11, with the labels that each got.

#547 New cache management strategy
  collect/cache/cache.go
  collect/cache/cache_test.go
  collect/collect.go
  collect/collect_test.go
  config/config.go
  config/config_test.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  rules_complete.toml
  types/event.go
  types/event_test.go
Labels: type: enhancement, version: bump minor

#548 Set content-type on marshalToFormat
  route/route.go
Labels: type: bug, version: bump patch

#556 Add command to query config metadata
  README.md
  config/config.go
  config/file_config.go
  config/mock.go
  route/route.go
Labels: type: enhancement, version: bump minor

#561 Extract Sent Cache to an interface for future expansion
  collect/cache/legacySentCache.go
  collect/cache/traceSentCache.go
  collect/collect.go
  collect/collect_benchmark_test.go
  collect/collect_test.go
  sample/dynamic_ema.go
  tools/loadtest/.gitignore
  types/event.go
Labels: type: enhancement, version: bump patch

#567 Add cuckoo-based drop cache
  collect/cache/cuckoo.go
  collect/cache/cuckooSentCache.go
  collect/cache/legacySentCache.go
  collect/cache/traceSentCache.go
  collect/collect.go
  collect/collect_benchmark_test.go
  collect/collect_test.go
  config/config.go
  config/config_test.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  go.mod
  go.sum
Labels: type: enhancement, version: bump minor

#571 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#569 On shutdown, remove ourself from the peers list
  app/app_test.go
  cmd/refinery/main.go
  config/config_test_reload_error_test.go
  internal/peer/peers.go
  internal/peer/peers_test.go
  internal/peer/redis.go
  internal/redimem/redimem.go
  sample/rules_test.go
  sharder/deterministic_test.go
Labels: type: enhancement, status: review needed, version: bump minor

#570 feat: Implement alternative sharding using rendezvous hash to improve dynamic scalability
  config/config.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  go.mod
  go.sum
  sharder/deterministic.go
  sharder/deterministic_test.go
Labels: status: review needed, version: bump minor

#572 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump
