Repository honeycombio/refinery, pull requests merged in 2022-06, with the labels that each got.

#464 maint: update action to auto-create issue for helm chart
  .github/workflows/release.yml
Labels: type: maintenance, version: no bump

#440 Add rule Scope configuration option to rules-based sampler
  config/config_test.go
  config/sampler_config.go
  rules_complete.toml
  sample/rules.go
  sample/rules_test.go
Labels: type: enhancement, status: info needed, version: bump minor, status: oncall

#465 Validate successful span scoped rules test
  sample/rules_test.go
Labels: type: maintenance, version: bump minor
