Repository honeycombio/refinery, pull requests merged in 2022-03, with the labels that each got.

#422 fix: error log event metadata
  app/app_test.go
  transmit/transmit.go
Labels: type: bug, version: bump patch

#424 Cache google ko deps between workflows
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#418 Add parsing for nested json fields in the rules sampler
  config/sampler_config.go
  go.mod
  go.sum
  rules_complete.toml
  sample/rules.go
  sample/rules_test.go
Labels: type: enhancement, version: bump minor

#431 Update husky to v0.10.3
  go.mod
  go.sum
Labels: version: bump patch, type: maintenance
