Repository honeycombio/refinery, pull requests merged in 2022-01, with the labels that each got.

#373 deps: bump libhoney & golang
  .circleci/config.yml
  go.mod
  go.sum
Labels: version: bump patch, type: dependencies, merge at will

#376 Prepare v1.8.1 release
  CHANGELOG.md
Labels: version: bump patch, type: maintenance

#378 docs: update rules example
  config/config_test.go
  rules_complete.toml
Labels: type: documentation, version: no bump

#382 Add retries when connecting to redis during init
  internal/peer/redis.go
Labels: type: enhancement, version: bump minor
