Repository honeycombio/refinery, pull requests merged in 2022-10, with the labels that each got.

#521 Cloud support
  internal/peer/redis.go
  sharder/deterministic.go
Labels: type: enhancement, version: bump minor

#532 Track span count and optionally add it to root
  Makefile
  collect/collect.go
  collect/collect_test.go
  config/config.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  sample/rules.go
  sample/rules_test.go
  types/event.go
Labels: type: enhancement, version: bump minor

#540 maint: add release file
  .github/release.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#543 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: type: maintenance, version: no bump, merge at will
