Repository honeycombio/refinery, pull requests merged in 2022-05, with the labels that each got.

#445 Prepare v1.14.0 release
  CHANGELOG.md
Labels: type: maintenance, version: bump minor

#447 README: remove incorrect mention of sending SIGUSR1 to trigger a configuration reload
  README.md
Labels: type: documentation

#450 Bump husky to 0.10.5
  go.mod
  go.sum
Labels: version: bump patch, type: maintenance

#455 Fix crash bug related to sharding
  sharder/deterministic.go
  sharder/deterministic_test.go
Labels: type: bug, version: bump patch

#457 Replace legacy with classic in README
  README.md
Labels: type: maintenance, version: no bump

#458 Create helm-chart issue on release
  .github/workflows/release.yml
Labels: type: enhancement, version: no bump

#459 Replace hand-rolled binary.BigEndian.Uint32 with the real deal
  sample/deterministic.go
  sharder/deterministic.go
Labels: version: bump patch, type: maintenance
