Repository honeycombio/refinery, pull requests merged in 2022-09, with the labels that each got.

#500 Add endpoints to help debug refinery rules
  README.md
  config/config.go
  config/config_test.go
  config/config_test_reload_error_test.go
  config/file_config.go
  config/mock.go
  go.mod
  internal/peer/peers_test.go
  route/otlp_trace_test.go
  route/proxy.go
  route/route.go
  route/route_test.go
  sample/sample.go
Labels: type: enhancement, version: bump minor

#498 Implement grpc-health-probe
  go.mod
  go.sum
  route/mock.go
  route/route.go
  route/route_test.go
Labels: type: enhancement, status: revision needed, version: bump minor

#499 Make gRPC ServerParameters configurable
  config/config.go
  config/config_test.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  route/route.go
Labels: type: enhancement, status: revision needed, version: bump minor

#504 Fix sample rate for late spans
  collect/collect.go
Labels: type: bug, version: bump patch

#503 Optionally record why a sample decision was made
  README.md
  app/app_test.go
  collect/cache/cache_test.go
  collect/collect.go
  collect/collect_benchmark_test.go
  collect/collect_test.go
  config/config.go
  config/config_test.go
  config/config_test_reload_error_test.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  internal/peer/file_test.go
  internal/peer/peers_test.go
  logger/logger_test.go
  metrics/metrics_test.go
  metrics/prometheus_test.go
  route/errors_test.go
  sample/deterministic.go
  sample/deterministic_test.go
  sample/dynamic.go
  sample/dynamic_ema.go
  sample/dynamic_ema_test.go
  sample/dynamic_test.go
  sample/rules.go
  sample/rules_test.go
  sample/sample.go
  sample/sample_test.go
  sample/totalthroughput.go
  sample/totalthroughput_test.go
  sample/trace_key_test.go
  sharder/deterministic_test.go
  sharder/sharder_test.go
  transmit/transmit_test.go
Labels: type: enhancement, version: bump minor

#505 Update Husky to latest
  go.mod
  go.sum
  route/otlp_trace.go
  route/otlp_trace_test.go
  route/route.go
Labels: type: enhancement, version: bump minor

#491 Added PeerManagement.Timeout config option
  .gitignore
  app/app_test.go
  cmd/refinery/main.go
  config/config.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  internal/peer/peers.go
  internal/peer/peers_test.go
  internal/peer/redis.go
  route/route.go
  sharder/deterministic_test.go
Labels: type: enhancement, status: revision needed, version: bump minor

#508 Add 'meta.refinery.original_sample_rate'
  collect/collect.go
  collect/collect_test.go
Labels: type: enhancement, status: revision needed, version: bump minor

#510 Prepare v1.16.0 release
  CHANGELOG.md
  OSSMETADATA
Labels: type: maintenance, version: bump minor

#511 Consolidate honeycomb metrics to use single lock & fix concurrent read/write
  metrics/honeycomb.go
Labels: type: bug, version: bump patch

#509 allow BatchTimeout to be overriden on the libhoney Transmission
  cmd/refinery/main.go
  config/config.go
  config/file_config.go
  config/mock.go
  config_complete.toml
Labels: type: enhancement, version: bump minor, status: oncall

#514 Allow adding extra fields to error logs
  app/app_test.go
  config/config.go
  config/config_test.go
  config/config_test_reload_error_test.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  internal/peer/peers_test.go
  logger/honeycomb.go
  metrics/honeycomb.go
  sample/sample_test.go
  transmit/transmit.go
Labels: type: enhancement, version: bump minor

#519 Fix variable shadowing bug
  metrics/honeycomb.go
  metrics/honeycomb_test.go
Labels: type: bug, merge at will

#517 prepare release v1.17.0
  CHANGELOG.md
Labels: version: bump minor

#523 Properly set metadata to values that will work.
  transmit/transmit.go
Labels: type: bug, version: bump patch
