Repository honeycombio/refinery, pull requests merged in 2022-02, with the labels that each got.

#388 Prepare v1.9.0 release
  CHANGELOG.md
Labels: type: maintenance, version: bump minor

#394 Fixed "honeeycomb" typo in log output when reloading config
  metrics/honeycomb.go
Labels: type: maintenance, version: no bump

#395 build: add ARM64 RPM artifact
  .circleci/config.yml
Labels: merge at will

#405 Prepare v1.11.0 release
  CHANGELOG.md
Labels: type: maintenance, version: bump minor

#409 Update aws-client orb to latest
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#410 feat: add support for env name from auth
  route/route.go
Labels: type: enhancement, version: bump major, version: bump minor
