Repository honeycombio/refinery, pull requests merged in 2023-03, with the labels that each got.

#627 chore: publish should only happen on main
  .circleci/config.yml
Labels: type: maintenance, version: no-bump

#623 feat: Add meta.refinery.reason to late spans
  collect/collect.go
  collect/collect_test.go
Labels: type: enhancement, version: bump patch, status: review needed

#621 feat: allow ability to add new attributes to refinery data
  collect/collect.go
  collect/collect_test.go
  config/config.go
  config/config_test.go
  config/file_config.go
  config/mock.go
  config_complete.toml
Labels: type: enhancement, status: review needed, version: bump minor, merge at will

#640 maint: Add labels to docker image
  build-docker.sh
Labels: version: no bump, no-changelog
