Repository honeycombio/refinery, pull requests merged in 2023-07, with the labels that each got.

#772 fix: Move Unknown log level to zero position
  config/level.go
Labels: version: bump patch

#778 fix: Add ability to handle k8s unit format
  config.md
  config/config_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  refinery_config.md
  rules.md
  tools/convert/templates/configV2.tmpl
Labels: version: bump patch

#774 fix: Add missing validation for LegacyMetrics APIKey
  config.md
  config/metadata/configMeta.yaml
  rules.md
  tools/convert/templates/configV2.tmpl
Labels: version: bump patch

#768 fix: hack a fix for adjustmentinterval not converting inside rules based samples
  tools/convert/ruleconvert.go
  tools/convert/ruleconvert_test.go
Labels: version: bump patch

#771 fix: Update file_config to honor GRPCServerParameters.Enabled
  config.md
  config/config.go
  config/config_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/mock.go
  route/route.go
  rules.md
  tools/convert/helpers.go
  tools/convert/templates/configV2.tmpl
Labels: version: bump patch

#779 maint: Update release notes
  RELEASE_NOTES.md
Labels: version: no bump, no-changelog

#782 fix: Update validate logic to use MemorySize
  config.md
  config/configLoadHelpers_test.go
  config/config_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/validate.go
  config/validate_test.go
  go.mod
  go.sum
  refinery_config.md
  rules.md
  tools/convert/helpers.go
  tools/convert/templates/configV2.tmpl
Labels: version: bump patch

#789 docs: General Improvements
  config.md
  config/metadata/configMeta.yaml
  refinery_config.md
  tools/convert/templates/cfg_docrepo.tmpl
  tools/convert/templates/cfg_docsite.tmpl
Labels: wip, type: documentation
