Repository honeycombio/refinery, pull requests merged in 2023-02, with the labels that each got.

#599 maint: bump grpc to 1.52.3
  go.mod
  go.sum
Labels: version: bump patch, type: dependencies

#593 feat: extend and unify metrics system
  app/app.go
  app/app_test.go
  cmd/refinery/main.go
  collect/collect.go
  collect/collect_test.go
  go.mod
  go.sum
  metrics/honeycomb.go
  metrics/honeycomb_test.go
  metrics/metrics.go
  metrics/metricsnamer.go
  metrics/mock.go
  metrics/nullmetrics.go
  metrics/prometheus.go
  route/route.go
  route/route_test.go
  sample/sample.go
  sample/sample_test.go
  sharder/deterministic_test.go
  transmit/transmit.go
  transmit/transmit_test.go
Labels: type: enhancement, version: bump patch, status: review needed

#594 feat: Stress Relief system
  app/app_test.go
  cmd/refinery/main.go
  collect/collect.go
  collect/collect_test.go
  collect/stressRelief.go
  config/config.go
  config/file_config.go
  config/mock.go
  config_complete.toml
  metrics/honeycomb.go
  route/route.go
  route/route_test.go
Labels: type: enhancement, status: review needed, version: bump minor

#604 perf: Improve performance of stress relief
  collect/stressRelief.go
  config/file_config.go
  config_complete.toml
Labels: type: enhancement, version: bump patch, status: review needed

#611 fix: do not send sample rate in dry run
  collect/collect.go
  collect/collect_test.go
Labels: type: bug, version: bump patch

#613 chore: Publish every build to honeycomb's ecr
  .circleci/config.yml
Labels: type: maintenance, version: no bump, no-changelog
