Repository honeycombio/refinery, pull requests merged in 2024-09, with the labels that each got.

#1309 fix: join peer list only after refinery is ready to accept traffic
  cmd/refinery/main.go
  internal/peer/file.go
  internal/peer/mock.go
  internal/peer/peers.go
  internal/peer/pubsub_redis.go
Labels: type: bug

#1313 docs: Sync Refinery docs content for 2.8
  config.md
  config/metadata/configMeta.yaml
  config_complete.yaml
  refinery_config.md
  tools/convert/templates/configV2.tmpl
Labels: merge at will

#1316 maint: run smoke test in CI
  .circleci/config.yml
  .gitignore
  Makefile
  build-docker.sh
  smoke-test/config-tls.yaml
  smoke-test/config.yaml
  smoke-test/docker-compose-tls.yaml
  smoke-test/docker-compose.yaml
Labels: type: maintenance

#1323 feat: Allow SendKey to be set via command line and env var
  config/cmdenv.go
  config/config_test.go
  config/file_config.go
Labels: type: enhancement

#1329 fix: assertion for ClusterSizer
  sample/rules.go
  sample/sample.go
Labels: type: bug

#1322 feat: Improve log messages to be more informative
  cmd/refinery/main.go
  collect/collect.go
  collect/stressRelief.go
  metrics/otel_metrics.go
  sharder/deterministic.go
Labels: type: enhancement

#1328 feat: Update Honeycomb logger to use EMAThroughput sampler
  logger/honeycomb.go
Labels: type: enhancement

#1346 maint: rename sent_reason_cache to kept_reason_cache
  collect/cache/cuckooSentCache.go
  collect/cache/kept_reason_cache_test.go
  collect/cache/kept_reasons_cache.go
  collect/collect.go
  types/event.go
Labels: type: maintenance

#1350 maint: Refactor metrics registration to streamline declaration and enable easier documentation generation
  app/app.go
  cmd/refinery/main.go
  collect/cache/cache.go
  collect/cache/cuckoo.go
  collect/cache/cuckooSentCache.go
  collect/cache/kept_reasons_cache.go
  collect/collect.go
  collect/stressRelief.go
  collect/stress_relief_test.go
  internal/health/health.go
  internal/peer/file.go
  internal/peer/pubsub_redis.go
  metrics/legacy.go
  metrics/legacy_test.go
  metrics/metrics.go
  metrics/metricsnamer.go
  metrics/mock.go
  metrics/multi_metrics.go
  metrics/multi_metrics_test.go
  metrics/nullmetrics.go
  metrics/otel_metrics.go
  metrics/prometheus.go
  metrics/prometheus_test.go
  pubsub/pubsub_goredis.go
  pubsub/pubsub_local.go
  route/route.go
  sample/deterministic.go
  sample/dynamic.go
  sample/dynamic_ema.go
  sample/ema_throughput.go
  sample/rules.go
  sample/sample.go
  sample/totalthroughput.go
  sample/windowed_throughput.go
  sample/windowed_throughput_test.go
  transmit/transmit.go
Labels: type: maintenance
