Repository honeycombio/refinery, pull requests merged in 2024-04, with the labels that each got.

#1077 feat: RedisMetricsRecorder
  centralstore/redis_metrics_recorder.go
  metrics/multi_metrics.go
Labels: type: enhancement

#1076 maint: Remove error return from (almost) all the get functions in config
  collect/cache/span_cache_basic.go
  collect/cache/span_cache_complex.go
  collect/central_collector.go
  collect/collect.go
  config/config.go
  config/config_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/mock.go
  internal/peer/file.go
  internal/peer/peers.go
  internal/peer/redis.go
  internal/redis/redis.go
  logger/honeycomb.go
  logger/logger.go
  logger/logrus.go
  route/otlp_trace.go
  route/proxy.go
  route/route.go
  service/debug/debug_service.go
  sharder/deterministic.go
  transmit/transmit.go
Labels: type: maintenance

#1085 feat: implement graceful shutdown for central store
  app/app_test.go
  centralstore/centralstore.go
  centralstore/localremotestore.go
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  centralstore/smartwrapper.go
  cmd/test_stores/tracegen.go
  collect/cache/cuckooSentCache.go
  collect/central_collector.go
  collect/central_collector_test.go
  collect/cycler.go
  config/file_config.go
  types/event.go
  types/event_test.go
Labels: type: enhancement

#1084 feat: add configuration for central collector
  centralstore/smartwrapper.go
  collect/central_collector.go
  collect/central_collector_test.go
  collect/panic_handler.go
  config/file_config.go
  config/metadata/configMeta.yaml
  go.mod
Labels: type: enhancement

#1090 fix: fix config reload flags
  config/metadata/configMeta.yaml
Labels: type: documentation

#1094 fix: do not exit from the processor and decider loop on first error
  collect/central_collector.go
  collect/central_collector_test.go
Labels: type: bug

#1093 feat: record metrics on an interval in central store
  app/app_test.go
  centralstore/centralstore.go
  centralstore/smartwrapper.go
  centralstore/smartwrapper_test.go
  collect/cache/span_cache_basic.go
  collect/cache/span_cache_complex.go
  collect/central_collector.go
  collect/central_collector_test.go
  collect/stressRelief.go
  config/file_config.go
  route/route.go
Labels: type: enhancement

#1091 fix: local store fixes
  app/app_test.go
  centralstore/centralstore.go
  centralstore/local_store.go
  centralstore/redis_store.go
  centralstore/smartwrapper_record_metrics_test.go
  centralstore/smartwrapper_test.go
  cmd/refinery/main.go
  cmd/test_stores/main.go
  collect/central_collector.go
  collect/central_collector_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  go.mod
  go.sum
  internal/peer/redis.go
  redis/redis.go
  sample/sample_test.go
  types/event.go
Labels: type: bug

#1099 feat: add health package
  internal/health/health.go
  internal/health/health_test.go
Labels: type: enhancement

#1098 feat: implement Gossiper interface
  internal/gossip/gossip.go
  internal/gossip/gossip_redis.go
  internal/gossip/gossip_redis_test.go
  redis/redis.go
  redis/test_harness.go
Labels: type: enhancement

#1096 feat: implement stress relief
  app/app_test.go
  centralstore/centralstore.go
  centralstore/local_store.go
  centralstore/redis_store.go
  centralstore/smartwrapper.go
  cmd/refinery/main.go
  collect/central_collector.go
  collect/central_collector_test.go
  collect/stressRelief.go
  collect/stressRelief/stress_relief.go
  collect/stressRelief/stress_relief_redis.go
  collect/stressRelief/stress_relief_test.go
  internal/gossip/gossip.go
  internal/gossip/gossip_redis.go
  route/route.go
  route/route_test.go
Labels: type: enhancement

#1106 fix: remove peer from injection graph
  cmd/refinery/main.go
  collect/stressRelief/stress_relief_test.go
Labels: type: enhancement

#1109 feat: write span in batch to redis
  centralstore/centralstore.go
  centralstore/local_store.go
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  centralstore/smartwrapper.go
  redis/redis.go
Labels: type: enhancement

#1110 feat: performance tweaks
  centralstore/centralstore.go
  centralstore/local_store.go
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  centralstore/smartwrapper.go
  centralstore/smartwrapper_record_metrics_test.go
  centralstore/smartwrapper_test.go
  cmd/test_stores/fake_refinery.go
  collect/central_collector.go
  collect/central_collector_test.go
  config/file_config.go
Labels: type: enhancement
