Repository honeycombio/refinery, pull requests merged in 2024-03, with the labels that each got.

#1019 maint: Update Husky to handle invalid content type errors
  go.mod
  go.sum
  route/errors.go
  route/otlp_trace.go
  route/otlp_trace_test.go
Labels: version: bump patch, type: maintenance

#1029 rel: prepare v2.4.3
  CHANGELOG.md
  RELEASE_NOTES.md
Labels: version: no bump, no-changelog

#1028 maint: group minor/patch dep updates
  .github/dependabot.yml
Labels: type: maintenance, version: no bump

#1021 feat: parallelize decider and tracing support for basic store
  centralstore/centralstore.go
  centralstore/localremotestore.go
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  centralstore/smartwrapper.go
  centralstore/smartwrapper_test.go
  cmd/test_stores/fake_refinery.go
  cmd/test_stores/main.go
  cmd/test_stores/otel_tracing.go
  cmd/test_stores/tracegen.go
  internal/otelutil/otel_tracing.go
  internal/redis/redis.go
Labels: type: enhancement

#1042 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, no-changelog

#1043 feat: support Classic Ingest Keys
  go.mod
  go.sum
  types/event.go
Labels: type: enhancement, version: bump minor, merge at will

#1018 feat: Shortcut evaluation of rules containing 'root.'
  sample/rules.go
  sample/rules_test.go
Labels: type: enhancement

#1058 maint: Bump protobuf
  go.mod
  go.sum
Labels: type: security

#1060 fix: deal with locking issues at startup
  metrics/legacy.go
  metrics/multi_metrics.go
  metrics/otel_metrics.go
  metrics/prometheus.go
Labels: version: bump patch
