Repository honeycombio/refinery, pull requests merged in 2024-11, with the labels that each got.

#1409 maint: Update OTel dependencies
  go.mod
  go.sum
Labels: type: maintenance

#1403 fix: reset redistribution delay on peer membership change
  collect/collect.go
  collect/collect_test.go
  collect/trace_redistributer.go
  collect/trace_redistributer_test.go
Labels: type: bug

#1412 feat: send kept trace decision in a separate goroutine
  collect/collect.go
  collect/collect_test.go
Labels: type: enhancement

#1413 feat: only enalbe stress relief for the entire cluster together
  collect/collect.go
  collect/stressRelief.go
  collect/stress_relief_test.go
Labels: type: enhancement

#1408 fix: deal with orphan traces and expired traces
  collect/collect.go
  collect/collect_test.go
  collect/stress_relief_test.go
  types/event.go
Labels: type: enhancement

#1387 maint: add comments about an edge case in SendKey
  README.md
Labels: type: maintenance

#1404 fix: replace api key with SendKey before transmission
  collect/collect.go
  collect/collect_test.go
  config/file_config.go
  config/file_config_test.go
  route/errors.go
  route/middleware.go
  route/otlp_logs.go
  route/otlp_logs_test.go
  route/otlp_trace.go
  route/otlp_trace_test.go
  route/route.go
  route/route_test.go
Labels: type: bug

#1419 feat: batch kept decisions
  collect/collect.go
  collect/collect_test.go
  collect/trace_decision.go
  collect/trace_decision_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
Labels: type: enhancement

#1418 docs: update config docs for compatability of using DryRun and EnableTraceLocality together
  config/metadata/configMeta.yaml
Labels: type: maintenance

#1421 feat: increase KeptDecisionSendInterval default value to 1s
  config/file_config.go
  config/metadata/configMeta.yaml
Labels: type: enhancement

#1423 fix: do not use trace object during processTraceDecisions
  collect/collect.go
  collect/trace_decision.go
  collect/trace_decision_test.go
Labels: type: enhancement

#1430 feat: compress kept trace decision message
  collect/collect_test.go
  collect/trace_decision.go
  collect/trace_decision_test.go
  go.mod
  go.sum
Labels: type: enhancement

#1433 fix: send all traffic through deterministic sampler during stress relief activated
  collect/collect.go
  collect/stressRelief.go
  collect/stress_relief_test.go
Labels: type: enhancement
