Repository honeycombio/refinery, pull requests merged in 2024-05, with the labels that each got.

#1115 fix: prevent data race when retrieve information about cuckoo cache
  collect/cache/cuckoo.go
  collect/cache/cuckooSentCache.go
Labels: type: bug

#1113 fix: improve performance for getting trace state from redis
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  centralstore/smartwrapper.go
  collect/central_collector.go
  collect/central_collector_test.go
  collect/stressRelief/stress_relief_redis.go
  redis/redis.go
Labels: type: enhancement

#1127 fix: break once we find parent ID field on a span
  route/route.go
Labels: type: bug

#1132 feat: add MetricsCycleRate config option for redis
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  collect/central_collector.go
  config/config.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/mock.go
Labels: type: enhancement

#1133 fix: make sure send_reason is attached to span metadata
  centralstore/redis_store.go
  collect/central_collector.go
  collect/central_collector_test.go
Labels: type: bug

#1135 feat: distribute workload for trace state management more efficiently
  centralstore/centralstore.go
  centralstore/local_store.go
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  centralstore/smartwrapper.go
  centralstore/smartwrapper_test.go
  collect/central_collector_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/mock.go
  redis/redis.go
Labels: type: enhancement

#1137 fix: make sure we can retrieve trace decisions made during stress relief
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  collect/central_collector.go
Labels: type: bug

#1141 feat: expire keys in redis based on TraceTimeout
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
Labels: type: enhancement

#1142 feat: turn manual GC back on
  collect/central_collector.go
Labels: type: enhancement

#1143 fix: make sure we record critical errors
  centralstore/redis_store.go
  centralstore/smartwrapper.go
  collect/central_collector.go
Labels: type: enhancement

#1146 fix: Update cache lookup to use read lock (#1145)
  route/route.go
Labels: type: bug

#1148 fix: make sure information for state machine is present before state changes
  centralstore/redis_store.go
  centralstore/redis_store_test.go
Labels: type: bug

#1163 fix: Fix docs formatting around list type
  rules_conditions.md
Labels: version: no bump

#1165 fix: correct race condition in OTel metrics
  metrics/otel_metrics.go
Labels: Cherrypick, Refinery 2
