Repository honeycombio/refinery, pull requests merged in 2024-08, with the labels that each got.

#1261 feat: redistribute remaining traces during shutdown
  app/app_test.go
  cmd/refinery/main.go
  collect/cache/cuckooSentCache.go
  collect/cache/traceSentCache.go
  collect/collect.go
  collect/collect_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  route/route.go
  sharder/single.go
Labels: type: enhancement

#1280 rel: prepare v2.7.1
  CHANGELOG.md
  RELEASE_NOTES.md
Labels: type: maintenance, version: no bump

#1291 maint: add a docker'd Redis TLS local setup
  Makefile
  smoke-test/.gitignore
  smoke-test/README.md
  smoke-test/config.yaml
  smoke-test/docker-compose.yaml
  smoke-test/rules.yaml
Labels: version: no bump, no-changelog

#1292 maint: Delete unused Dockerfile
  Dockerfile
Labels: type: maintenance, version: no bump

#1293 maint: Add warning about cli flags
  config/cmdenv.go
  config/metadata/configMeta.yaml
Labels: type: maintenance, type: documentation, version: no bump
