Repository honeycombio/refinery, pull requests merged in 2024-10, with the labels that each got.

#1358 feat: Record original user agent for spans and logs
  app/app_test.go
  route/otlp_logs.go
  route/otlp_logs_test.go
  route/otlp_trace.go
  route/otlp_trace_test.go
  route/route.go
Labels: type: enhancement

#1367 rel: Prepare 2.8.3 release
  CHANGELOG.md
  RELEASE_NOTES.md
Labels: type: maintenance

#1372 rel: Prepare 2.8.3 release (updated)
  CHANGELOG.md
  RELEASE_NOTES.md
Labels: type: maintenance

#1373 docs: Update configMeta.yaml with capitalization fixes
  config/metadata/configMeta.yaml
Labels: type: documentation

#1386 feat: Log response bodies when sending events to Honeycomb
  transmit/transmit.go
Labels: type: enhancement

#1388 fix: use current node address as default peer list
  internal/peer/pubsub_redis.go
Labels: type: bug

#1359 feat: Update in-memory trace cache to use LRU instead of ring buffer
  collect/cache/cache.go
  collect/cache/cache_test.go
  collect/collect.go
  collect/collect_test.go
  config/metadata/configMeta.yaml
Labels: type: enhancement

#1398 maint(deps): update husky to v0.31.0
  go.mod
  go.sum
Labels: version: bump patch, type: maintenance, merge at will

#1402 feat: send drop decisions in batch
  collect/collect.go
  collect/collect_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
Labels: type: enhancement

#1405 fix: deal with orphan traces in trace cache
  collect/cache/cache.go
  collect/collect.go
  collect/collect_test.go
Labels: type: enhancement

#1406 fix: explictly assign float64 type for trace cache metrics
  collect/cache/cache.go
Labels: type: bug
