Repository honeycombio/refinery, pull requests merged in 2024-07, with the labels that each got.

#1218 feat: add otel tracing support for Refinery internal operations
  .gitignore
  cmd/refinery/main.go
  config/cmdenv.go
  config/config.go
  config/configLoadHelpers.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/mock.go
  go.mod
  go.sum
  internal/otelutil/otel_tracing.go
Labels: type: enhancement

#1224 docs: update vulnerability reporting process
  SECURITY.md
Labels: type: documentation, version: no bump

#1228 maint: change targeted arch to arm for local development Dockerfile
  Dockerfile
Labels: type: maintenance

#1236 fix: Root spans must have a non-empty parent ID field
  collect/collect.go
  collect/collect_test.go
Labels: type: bug

#1240 fix: remove otel-config-go as a dependency
  go.mod
  go.sum
  internal/otelutil/otel_tracing.go
Labels: type: enhancement

#1221 feat: use pub/sub for stress relief
  collect/collect.go
  collect/collect_test.go
  collect/mockCollector.go
  collect/stressRelief.go
  collect/stress_relief_test.go
  config/file_config.go
  go.mod
  go.sum
  internal/peer/file.go
  internal/peer/file_test.go
  internal/peer/mock.go
  internal/peer/peers.go
  internal/peer/pubsub_redis.go
  route/route.go
Labels: type: enhancement

#1244 maint: Update licenses
  LICENSES/crypto/internal/boring/LICENSE
  LICENSES/github.com/dgryski/go-rendezvous/LICENSE
  LICENSES/github.com/google/uuid/LICENSE
  LICENSES/github.com/honeycombio/husky/LICENSE
  LICENSES/github.com/honeycombio/husky/NOTICE
  LICENSES/github.com/jonboulle/clockwork/LICENSE
  LICENSES/github.com/redis/go-redis/v9/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/otlp/otlptrace/LICENSE
  LICENSES/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp/LICENSE
  LICENSES/vendor/golang.org/x/crypto/LICENSE
  LICENSES/vendor/golang.org/x/net/LICENSE
  LICENSES/vendor/golang.org/x/text/LICENSE
  Makefile
Labels: merge at will

#1259 refactor: Remove error returns from config functions, fix tests.
  app/app_test.go
  cmd/refinery/main.go
  collect/collect.go
  collect/collect_test.go
  config/config.go
  config/config_test.go
  config/config_test_reload_error_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/mock.go
  internal/peer/file.go
  internal/peer/peers_test.go
  internal/peer/pubsub_redis.go
  logger/honeycomb.go
  logger/logger.go
  logger/logrus.go
  pubsub/pubsub_goredis.go
  route/otlp_trace_test.go
  route/proxy.go
  route/route.go
  sample/sample.go
  service/debug/debug_service.go
  test/config.yaml
  transmit/transmit.go
Labels: type: maintenance
