Repository honeycombio/refinery, pull requests merged in 2024-02, with the labels that each got.

#979 docs: include a warning about surprising not-exists behavior
  RELEASING.md
  config/metadata/rulesMeta.yaml
  rules_conditions.md
Labels: type: documentation

#989 chore: fix license tracking
  Makefile
Labels: type: maintenance, version: no bump

#990 chore: Revert "chore: fix license tracking (#989)"
  Makefile
Labels: type: maintenance, version: no bump

#994 chore: consolidate routine dependency updates
  go.mod
  go.sum
Labels: version: bump patch, type: dependencies

#991 fix: flaky TestOriginalSampleRateIsNotedInMetaField
  collect/collect_test.go
Labels: type: bug, version: no bump

#995 docs: Add sampler default intervals to docs
  config/metadata/rulesMeta.yaml
  refinery_rules.md
  rules.md
Labels: type: documentation, version: no bump

#1007 fix: Fix a typo from PR #1006
  sample/rules.go
Labels: type: documentation, version: no bump, no-changelog

#1012 rel: prepare v2.4.1
  CHANGELOG.md
  RELEASE_NOTES.md
  RELEASING.md
  config.md
  config/metadata/rulesMeta.yaml
  config_complete.yaml
  refinery_rules.md
  rules.md
  tools/convert/configDataNames.txt
  tools/convert/minimal_config.yaml
  tools/convert/templates/configV2.tmpl
Labels: type: maintenance, version: no bump, no-changelog

#1013 feat: add tracing
  centralstore/smartwrapper.go
  centralstore/smartwrapper_test.go
  cmd/test_stores/main.go
  go.mod
  go.sum
Labels: type: enhancement

#1014 feat: properly handle keep state and timestamp for state transition
  centralstore/redis_store.go
  centralstore/redis_store_test.go
  centralstore/smartwrapper_test.go
  cmd/test_stores/main.go
  internal/redis/redis.go
Labels: type: enhancement

#1017 rel: prepare v2.4.2
  CHANGELOG.md
  RELEASE_NOTES.md
Labels: version: no bump, no-changelog
