Repository honeycombio/refinery, pull requests merged in 2025-08, with the labels that each got.

#1635 feat: implement retry for direct transmit
  transmit/direct_transmit.go
  transmit/direct_transmit_test.go
Labels: type: enhancement

#1646 fix: update CacheCapacity description
  config/metadata/configMeta.yaml
Labels: type: documentation

#1661 fix: make sure all transmit metrics have correct libhoney prefix
  transmit/direct_transmit.go
  transmit/direct_transmit_test.go
Labels: type: bug

#1666 maint: (BREAKING) remove CacheCapacity functionality
  app/app_test.go
  collect/cache/cache.go
  collect/cache/cache_test.go
  collect/collect.go
  collect/collect_test.go
  config/config_test.go
  config/file_config.go
  route/otlp_trace_test.go
Labels: version: bump major, breaking-change

#1672 maint: remove UpstreamBufferSize and PeerBufferSize from stress relief
  app/app_test.go
  cmd/refinery/main.go
  collect/stressRelief.go
  config/config.go
  config/config_serializer.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/mock.go
  rules_complete.yaml
Labels: breaking-change

#1667 feat: config option deprecation
  cmd/refinery/main.go
  config/configLoadHelpers.go
  config/configLoadHelpers_test.go
  config/config_test.go
  config/file_config.go
  config/metadata.go
  config/metadata/configMeta.yaml
  config/validate.go
  config/validate_test.go
  config/version.go
  config/version_test.go
  go.mod
  tools/convert/main.go
Labels: type: enhancement
