Repository honeycombio/refinery, pull requests merged in 2025-04, with the labels that each got.

#1515 docs: add missing metrics and extra details
  config.md
  config/metadata/configMeta.yaml
  config/metadata/rulesMeta.yaml
  config_complete.yaml
  metrics.md
  refinery_config.md
  refinery_rules.md
  rules.md
  tools/convert/configDataNames.txt
  tools/convert/minimal_config.yaml
  tools/convert/templates/configV2.tmpl
Labels: type: documentation

#1526 docs: some copyedits from docs
  config.md
  config/metadata/configMeta.yaml
  config/metadata/rulesMeta.yaml
  config_complete.yaml
  refinery_config.md
  refinery_rules.md
  rules.md
  tools/convert/templates/configV2.tmpl
Labels: type: documentation, version: no bump

#1542 maint: prepare for release v2.9.5
  CHANGELOG.md
  RELEASE_NOTES.md
Labels: no-changelog
