Repository honeycombio/refinery, pull requests merged in 2025-05, with the labels that each got.

#1559 maint: update husky to v0.36.0
  go.mod
  go.sum
Labels: type: maintenance

#1562 fix: Add valuetype to rules datatype
  config/metadata/rulesMeta.yaml
  refinery_rules.md
  rules.md
Labels: type: bug

#1564 maint: Add autogenerated comment to config templates
  config.md
  metrics.md
  refinery_config.md
  refinery_rules.md
  rules.md
  tools/convert/templates/cfg_docrepo.tmpl
  tools/convert/templates/cfg_docsite.tmpl
  tools/convert/templates/metrics.tmpl
  tools/convert/templates/rules_docrepo.tmpl
  tools/convert/templates/rules_docsite.tmpl
Labels: type: maintenance

#1565 docs: update _router_otlp description
  metrics.md
  route/route.go
  tools/convert/metricsMeta.yaml
Labels: type: documentation
