Repository honeycombio/refinery, pull requests merged in 2025-09, with the labels that each got.

#1681 fix: dataset name should only be url encoded once
  transmit/direct_transmit.go
  transmit/direct_transmit_test.go
Labels: type: bug

#1694 fix: set default sizes for queues
  config/file_config.go
Labels: type: bug

#1696 maint: update husky to v0.39.0
  collect/collect_test.go
  go.mod
  go.sum
  route/otlp_trace_test.go
  transmit/direct_transmit_test.go
Labels: type: maintenance

#1692 feat: allow deprecating an entire config group
  config/config_test.go
  config/metadata.go
  config/validate.go
  config/validate_test.go
  config/version.go
  config/version_test.go
  tools/convert/helpers.go
Labels: version: bump major, breaking-change

#1691 maint: remove deprecated LegacyMetrics
  cmd/refinery/main.go
  config/cmdenv.go
  config/config.go
  config/configLoadHelpers.go
  config/config_serializer.go
  config/config_test.go
  config/file_config.go
  config/metadata/configMeta.yaml
  config/mock.go
  metrics/legacy.go
  metrics/legacy_test.go
  metrics/multi_metrics.go
  metrics/multi_metrics_test.go
Labels: version: bump major, breaking-change
