Repository honeycombio/refinery, pull requests merged in 2025-07, with the labels that each got.

#1617 perf: reduce lock contention for internal metrics
  cmd/refinery/main.go
  logger/honeycomb.go
  metrics/legacy.go
  metrics/legacy_test.go
  metrics/metrics.go
  metrics/multi_metrics.go
  metrics/multi_metrics_test.go
  metrics/otel_metrics.go
  metrics/prometheus.go
Labels: type: enhancement

#1623 ci: extend deadline for a wait in a flaky test
  collect/collect_test.go
Labels: type: maintenance, version: no bump

#1627 fix: correct type for processing a span from a peer
  collect/collect.go
Labels: type: bug, version: bump patch

#1631 fix: implement missing libhoney metrics in DirectTransmit
  transmit/direct_transmit.go
  transmit/direct_transmit_test.go
  types/payload_test.go
Labels: type: enhancement
